"""
视频编辑工具集
Video Editing Tools - 智能视频裁切、视频合并、预览功能
"""

from .edit_video import NODE_CLASS_MAPPINGS as CROP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_DISPLAY_MAPPINGS
from .mearge_video import NODE_CLASS_MAPPINGS as MERGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_DISPLAY_MAPPINGS

# 合并所有视频编辑节点映射
VIDEO_EDITING_NODE_CLASS_MAPPINGS = {**CROP_MAPPINGS, **MERGE_MAPPINGS}
VIDEO_EDITING_NODE_DISPLAY_NAME_MAPPINGS = {**CROP_DISPLAY_MAPPINGS, **MERGE_DISPLAY_MAPPINGS}

__all__ = ["VIDEO_EDITING_NODE_CLASS_MAPPINGS", "VIDEO_EDITING_NODE_DISPLAY_NAME_MAPPINGS"]