"""
RSS内容处理工具集
RSS Content Processing Suite - 集成到ComfyUI Shenglin节点包
"""

# 基础RSS工具节点
from .RSSFeedNode import NODE_CLASS_MAPPINGS as RSS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RSS_DISPLAY_MAPPINGS
from .RSSTextProcessor import NODE_CLASS_MAPPINGS as PROCESSOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROCESSOR_DISPLAY_MAPPINGS
from .RSSCacheManager import NODE_CLASS_MAPPINGS as CACHE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CACHE_DISPLAY_MAPPINGS
from .ArticleExtractor import NODE_CLASS_MAPPINGS as EXTRACTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXTRACTOR_DISPLAY_MAPPINGS

# 智能RSS分析节点
from .MultiRSSCollector import NODE_CLASS_MAPPINGS as MULTI_RSS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTI_RSS_DISPLAY_MAPPINGS
from .BatchArticleExtractor import NODE_CLASS_MAPPINGS as BATCH_EXTRACTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_EXTRACTOR_DISPLAY_MAPPINGS
from .ContentDeduplicator import NODE_CLASS_MAPPINGS as DEDUP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DEDUP_DISPLAY_MAPPINGS
from .TopicClusteringEngine import NODE_CLASS_MAPPINGS as CLUSTERING_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLUSTERING_DISPLAY_MAPPINGS
from .TopicReportGenerator import NODE_CLASS_MAPPINGS as REPORT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as REPORT_DISPLAY_MAPPINGS
from .ContentExporter import NODE_CLASS_MAPPINGS as EXPORTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXPORTER_DISPLAY_MAPPINGS
from .SelectedTopicViewer import NODE_CLASS_MAPPINGS as TOPIC_VIEWER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TOPIC_VIEWER_DISPLAY_MAPPINGS

# 合并所有RSS节点映射
RSS_NODE_CLASS_MAPPINGS = {
    **RSS_MAPPINGS,
    **PROCESSOR_MAPPINGS,
    **CACHE_MAPPINGS,
    **EXTRACTOR_MAPPINGS,
    **MULTI_RSS_MAPPINGS,
    **BATCH_EXTRACTOR_MAPPINGS,
    **DEDUP_MAPPINGS,
    **CLUSTERING_MAPPINGS,
    **REPORT_MAPPINGS,
    **EXPORTER_MAPPINGS,
    **TOPIC_VIEWER_MAPPINGS
}

RSS_NODE_DISPLAY_NAME_MAPPINGS = {
    **RSS_DISPLAY_MAPPINGS,
    **PROCESSOR_DISPLAY_MAPPINGS,
    **CACHE_DISPLAY_MAPPINGS,
    **EXTRACTOR_DISPLAY_MAPPINGS,
    **MULTI_RSS_DISPLAY_MAPPINGS,
    **BATCH_EXTRACTOR_DISPLAY_MAPPINGS,
    **DEDUP_DISPLAY_MAPPINGS,
    **CLUSTERING_DISPLAY_MAPPINGS,
    **REPORT_DISPLAY_MAPPINGS,
    **EXPORTER_DISPLAY_MAPPINGS,
    **TOPIC_VIEWER_DISPLAY_MAPPINGS
}

__all__ = ["RSS_NODE_CLASS_MAPPINGS", "RSS_NODE_DISPLAY_NAME_MAPPINGS"]
